# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - automl

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mlauto.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d8dbc19bd6414a6981da38b46d7cb960 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_fe0f19ce7268491695dcb86a6c18b654 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_d8dbc19bd6414a6981da38b46d7cb960 }}/automl:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'automl'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_98bfbac7552a40c89a12d79de42185f3 }}
        images: 'mlauto.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d8dbc19bd6414a6981da38b46d7cb960 }}/automl:${{ github.sha }}'