# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - automl

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mlauto.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_76248c7d4843499b802ca7879f4c83cf }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5dc6c315329e415aa8565ddc0dc0ddff }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mlauto.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_76248c7d4843499b802ca7879f4c83cf }}/mlauto/automl:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'automl'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2bb54fe20dcc4b4283d88c413699361d }}
        images: 'mlauto.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_76248c7d4843499b802ca7879f4c83cf }}/mlauto/automl:${{ github.sha }}'